### ISSUE TITLE
Add ability to display fans as percentage number instead of animation

### ISSUE THREAD

**Issue by mtehonica** [t0nyz0/BambuBoard#5]
Would it be possible to have an option to display the fan percentage as a number rather than the animation?

**Comment by t0nyz0** [comment]
I'll add this ability in the next update

**Comment by t0nyz0** [comment]
I just released **v1.0.8**, this release contains the requested percentage of fan speed.  You can have the fan icon, percentage or both. 

Before upgrading I would make a copy of your config.json so you dont have to retype it again. 
Add these two values:
![image](https://github.com/user-attachments/assets/c2427ac9-9cd5-444d-8f3d-32b77972d4e8)

Result:
![image](https://github.com/user-attachments/assets/b22a8025-14b0-4046-9c89-9b9c09c6bf23)

Please let me know if you encounter any issues with the build.

**Comment by mtehonica** [comment]
Hmm, not able to get this to work using v1.0.8.

config.json
![image](https://github.com/user-attachments/assets/fc342f5b-9da2-4399-8427-08112903480a)

![image](https://github.com/user-attachments/assets/ea6d96c2-8682-453a-8266-7e45f5de60ed)

Fan section of page source
![image](https://github.com/user-attachments/assets/b7fa6961-6d24-49aa-ae4f-646d95d39fca)

**Comment by t0nyz0** [comment]
Download the latest again, I forgot to remove my testing code. That should fix it.

**Comment by mtehonica** [comment]
No dice :/

Verified I have the latest version...
<img width="1070" alt="image" src="https://github.com/user-attachments/assets/fb28f58f-d101-4294-b368-1a6427a52b73">

**Comment by t0nyz0** [comment]
Interesting, that should of worked. 

Each preference change will require a restart. If you are running it using pm2 do something like this:
`pm2 restart bambuConnection.js`

I'll rebuild it in a few minutes and retest everything.

**Comment by mtehonica** [comment]
Still not able to figure out the problem with this issue. I've completely redeployed multiple times and still not able to get it working. I even hardcoded the displayFanPercentages in the Preferences section of the code and still wouldn't work, so I don't think its a config file issue. Tried a private browser to make sure it wasn't a caching issue.

![image](https://github.com/user-attachments/assets/ac3bd4d5-6321-48fb-be5b-9f2d514ced06)

**Comment by t0nyz0** [comment]
This is an odd issue, just tested with beta testers and they all show it working on their builds. 
https://www.youtube.com/live/QUaPWNoGo9E?si=wZBawaBPnnifXVZx

I'm guessing somehow your build is cached. The most important of these files is script.js both in the main folder, and if you are using OBS, you have to update the one in the widgets folder (/fans/fans_script.js).. If you are using OBS mode, go to fans_script.js and see if line this on line 118:
`$("#fan1-percent").text(convertToPercentage(fan1Speed));`

`sudo nano ./widgets/fans/FANS_script.js`
![image](https://github.com/user-attachments/assets/9449eec8-c0e1-46b8-bb69-30af03fdf10f)


Another way to test is check to see what value the settings is returning on the webservice, you can do that by going to this url:
http://ip_address:3000/preference-fan-percentages

That should show "true"

**Comment by mtehonica** [comment]
Man, how strange, really can't figure this out. I definitely have the most recent files.

<img width="874" alt="image" src="https://github.com/user-attachments/assets/0c0e4043-a1a2-40cf-a1e0-cf5f6c8d57ad">

<img width="581" alt="image" src="https://github.com/user-attachments/assets/aae27304-7683-43ba-8e39-c583bfedf8eb">

I'm running this in a Docker container and passing port 7777 on my Docker host to port 7777 in the container, which is what I've configured in the config - `"BambuBoard_httpPort": 7777`

Are there any other ports that need to be opened to allow the webservice to be accessed?

**Comment by t0nyz0** [comment]
Port 3000, sorry I should of mentioned that in the documentation somewhere

Wow and the webservice returns the true value, now I'm really puzzled.

**Comment by t0nyz0** [comment]
I dont think it being in a docker instance would matter, but I'll reach out to someone else I know that runs it that way and see if they are running into any issues.

If you have access to the browser its running on, I would pull up the developer tools in the menu and see if the console shows any errors. 
<img width="942" alt="image" src="https://github.com/user-attachments/assets/cf4a7a2e-13b7-4461-84d1-59286421fb4b">

**Comment by mtehonica** [comment]
Yup, now we're making progress.

<img width="1707" alt="image" src="https://github.com/user-attachments/assets/fde084ae-fffb-4c24-84f4-b2ef0eea3492">

So next problem is that 3000 is already in use for another Docker container. I mapped port `3333` on my host to `3333` in the container and manually changed the port in bambuConnection.js to `3333` and restarted the container/service but still get errors in the browser console about it trying to access port 3000.

<img width="501" alt="image" src="https://github.com/user-attachments/assets/2cec78d5-d8f4-45b5-abbb-ffe3a756de27">

**Comment by t0nyz0** [comment]
If you can test this update. In **bambuConnection.js** replace line 54 with this:
```
  origin: ['http://172.16.150.247:7777', 'http://localhost:7777'],
  methods: 'GET,HEAD,PUT,PATCH,POST,DELETE',
  credentials: true,
  allowedHeaders: 'Content-Type, Authorization'
```

**Comment by t0nyz0** [comment]
I see there is a bug with switching the port from 3000. 

Not difficult to fix. I'll put that into the next update.

**Comment by mtehonica** [comment]
> If you can test this update. In **bambuConnection.js** replace line 54 with this:
> 
> ```
>   origin: ['http://172.16.150.247:7777', 'http://localhost:7777'],
>   methods: 'GET,HEAD,PUT,PATCH,POST,DELETE',
>   credentials: true,
>   allowedHeaders: 'Content-Type, Authorization'
> ```

After making those changes and restarting, left with these errors still.

<img width="1710" alt="image" src="https://github.com/user-attachments/assets/5bb995f9-9d61-47ee-b7dc-1f82b7448118">

**Comment by t0nyz0** [comment]
Now we a getting close. I think I can resolve it in code now with a few changes. 

In the meantime, there are 4 lines of code that need that 3000 port manually updated in **script.js**
57
63
1196
1213

I'd change those next and retest.

**Comment by t0nyz0** [comment]
> > If you can test this update. In **bambuConnection.js** replace line 54 with this:
> > ```
> >   origin: ['http://172.16.150.247:7777', 'http://localhost:7777'],
> >   methods: 'GET,HEAD,PUT,PATCH,POST,DELETE',
> >   credentials: true,
> >   allowedHeaders: 'Content-Type, Authorization'
> > ```
> 
> After making those changes and restarting, left with these errors still.
> 
> <img alt="image" width="1710" src="https://private-user-images.githubusercontent.com/482973/358442393-5bb995f9-9d61-47ee-b7dc-1f82b7448118.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODg3ODIsIm5iZiI6MTcyMzc4ODQ4MiwicGF0aCI6Ii80ODI5NzMvMzU4NDQyMzkzLTViYjk5NWY5LTlkNjEtNDdlZS1iN2RjLTFmODJiNzQ0ODExOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwNjA4MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmZlYTYzMGJiNmJhMTk3MWFjNGZiNjcyNzRlNmEwYTZiNjE0MDA4YWMxMGZmYjhjZDg1MmVjYTU3ZjY2YjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MP8uR5eqI7HHeRF_Oc49b2KZ2VBVQ0kU1XkaiNRXSNk">

I just pushed out v1.0.9. 

I ended up rewriting a large portion of the backend code to no longer use 2 webserver ports. That should solve the CORS issue you were running into with the hard coded port numbers. 

If you can test again and let me know how this version works for you.

Overall this version is more secure, more efficient and cleaner code.. should work better overall. Maybe even solve the login issue you were having on the other ticket.

**Comment by mtehonica** [comment]
No errors in the console anymore but not much change otherwise.

![image](https://github.com/user-attachments/assets/134e0ed8-23c7-4a5d-9c41-64dbf6bcabad)

It does retrieve my config value changes when I make them.

![image](https://github.com/user-attachments/assets/e434ba72-9a17-4460-9188-2de8324abf81)
![image](https://github.com/user-attachments/assets/11bb5e35-b055-4828-badd-3fa6620a5d18)

Not sure if it's related but this error output is new

```
Error: ReferenceError: AbortController is not defined
    at fetchWithTimeout (/app/bambuConnection.js:61:22)
    at /app/bambuConnection.js:82:36
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at SendStream.error (/app/node_modules/serve-static/index.js:121:7)
```

**Comment by t0nyz0** [comment]
Ok, AbortController error, likely due to older version of Node. I'm on version 18, can you let me know what version you are on?  If its lower than 16, I can add a requirement for 16+ in the app, so that it will automatically upgrade your node when installed.
Or if you need a version lower than 16 for a reason, I can try to code something that does not require node 16+. 

Run this and let me know
`node -v`

**Comment by mtehonica** [comment]
```
root@4149839c03af:/app# node -v
v12.22.9
```

No specific reason for that version, that's just what is automatically installed in my Ubuntu container when I do a:

`RUN apt update -y ; apt upgrade -y ; apt full-upgrade -y ; apt install nodejs -y ; apt install npm -y`

**Comment by t0nyz0** [comment]
Thats solid info, I didnt realize that Ubuntu shipped with such a low version. Id rather support lower versions in that case.

I'm currently testing v1.1.0 in a branch.. If all goes well I'll publish this shortly

**Comment by mtehonica** [comment]
Sounds good, let me know if you want me to do any testing on that specific branch. I can just point my container build at that branch instead of main.

**Comment by t0nyz0** [comment]
Give it a go now, I pushed 1.1.0 to main branch

**Comment by mtehonica** [comment]
Great news, everything is working perfectly now!

![image](https://github.com/user-attachments/assets/58ee0bd8-1678-4fd5-b988-48cd8cef1e06)

I do have a new enhancement request though that I'll open a new issue for :)

**Comment by t0nyz0** [comment]
NICE! Appreciate your help with this, I learned alot.
